### ISSUE TITLE
Аргумент 'use_line_collection' в Первом разделе

### ISSUE THREAD

**Issue by Rashid-S** [capitanov/dsp-theory#1]
В разделе "Цифровая обработка сигналов - 1" в 24-й строке непонятный аргумент - 'use_line_collection'. С ним выдается сообщение
```
TypeError                                 Traceback (most recent call last)
<ipython-input-5-93d98a420581> in <module>
     22     plt.subplot(1, 3, i+1)
     23     plt.title(t_titles[i])
---> 24     plt_sel(i, t, x, use_line_collection=True)
     25     plt.xlim([0, 1])
     26     plt.yticks(np.linspace(np.floor(np.min(x)), np.ceil(np.max(x)), 9))

<ipython-input-5-93d98a420581> in plt_sel(s, *args, **kwargs)
     10         return plt.plot(*args)
     11     if s == 1:
---> 12         return plt.stem(*args, **kwargs)
     13     if s == 2:
     14         return plt.step(*args)

TypeError: stem() got an unexpected keyword argument 'use_line_collection'
```
и отрисовывет форму аналогового сигнала.
Если убрать этот аргумент, то все получается хорошо.

**Comment by Rashid-S** [comment]
Точнее, если убрать аргумент 'use_line_collection' , то аналоговый и дискретный отрисовываются нормально. А в квантованном не отрисовывется сетка графика

**Comment by capitanov** [comment]
«use_line_collections» это атрибут графика в формате `stem`. Применяется в данном случае только к stem, так как в plot и step не передаются *kwargs*. У меня без этого атрибута выдает ошибку в отрисовке stem.

Тут подробнее:
https://matplotlib.org/3.1.0/api/_as_gen/matplotlib.pyplot.stem.html

**Comment by Rashid-S** [comment]
> «Use_line_collections» это атрибут графика в формате `stem`. Применяется в данном случае только к стеблю, так как в сюжетном и ступенчатом не передается _kwargs_ . Вы делаете ошибку в отрисовке.
> 
> Тут подробнее: 
> https://matplotlib.org/3.1.0/api/_as_gen/matplotlib.pyplot.stem.html

Странно, у меня наоборот

**Comment by capitanov** [comment]
Из описания по ссылке:
matplotlib.pyplot.stem(*args, linefmt=None, markerfmt=None, basefmt=None, bottom=0, label=None, **use_line_collection**=False, data=None)

У `stem()` такой атрибут есть.
